# Generated by Django 6.0.1 on 2026-02-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_kind_alter_bb_price_alter_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('Купля-продажа', [('b', 'Куплю'), ('s', 'Продам')]), ('Обмен', [('c', 'Обменяю')])], default='s', max_length=1, verbose_name='Тип объявления'),
        ),
    ]
