# Generated by Django 6.0.1 on 2026-03-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_remove_bb_id_bb_kind_and_more'),
        ('bboard', '0004_alter_bb_kind'),
    ]

    operations = [
    ]
